language: node_js
node_js:
- '12'
install:
- npm install
script:
- npm run build:npm
deploy:
  provider: npm
  email: misu007.github@gmail.com
  api_key:
    secure: oubJU1Phg5DfC+AKxKRRE/dCYXRAYgqLqWpGkzC9h3Dtv/YXPpUDhbbCuREEduKHcovWN8MP52FvitVUKTRNfPZMeqRdraZuehflCfjFKHy9cDI6KTtMLn+z9GQSHyKcHzuz/+ok3DZtmGKJrsG9dWhl0qV673JuvJK+H4etF8lST+pu99BsgcWKja9zEVI/Ucjmj77RqT1NMJPg85XZBICgSnbqpone2TFEWZTgMH/Cj1pwhE9tMcfaSmhC8a+FyskVHw6NizOMj85QvYiiiZuTA4DOkR7BawjkYb4K3GNH4sFQW9A97CJbXQH+FJEXZ2ho1sPYjtbMSukirJwsoJZeoPWETBvRNLW1mmrTgca+cM1YqLTPIgqIHV9XcCQJXGFEhapiafpAjeKzkhgXHeaekeIFVZzt2dD5Umu//sxgApprp1R20fxRtXNTwxgRVr/7OOqmz//imNMdEfkVwtUSW7gVmk1xXG0YK+oDDCSZgyNAHs9zmFaVWiAJeMlPGCIGMsDcavWR2KKs9gt7VXtBrYvmGwrD8WQPdFF85gvYl0MZSrVlEaQu0rubNEhr1zPGhURoGguZDPA+RcZSjJTVB+BCgJz+3AasKLK0Po24yD8KEVjoyJSczyoHga7wh2S6H4d7CKTypI0bE/R2oo1fYWg6SBF1wUt/Cj5N+c4=
  on:
    tags: true
