language: node_js
node_js:
- '12.16'
install:
- npm install
script:
- npm run build:npm
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
  skip_cleanup: true
